(dp1
S'output'
p2
S''
sS'layer'
p3
S'/home/ian/web2py/applications/paideia/controllers/util.py'
p4
sS'code'
p5
S'# coding: utf8\n\nimport datetime\n\ndef copytimes():\n    dates = db(db.question_records.id > 0).select()\n    for d in dates:\n        t = datetime.time(12,0)\n        date1 = d.last_right\n        dt1 = datetime.datetime.combine(date1, t)\n        date2 = d.last_wrong\n        dt2 = datetime.datetime.combine(date2, t)\n        d.update_row(last_right = dt1, last_wrong = dt2)\n         \n        \nresponse._vars=response._caller(copytimes)\n'
p6
sS'snapshot'
p7
(dp8
sS'traceback'
p9
S'Traceback (most recent call last):\n  File "/home/ian/web2py/gluon/restricted.py", line 194, in restricted\n    exec ccode in environment\n  File "/home/ian/web2py/applications/paideia/controllers/util.py", line 16, in <module>\n  File "/home/ian/web2py/gluon/globals.py", line 149, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ian/web2py/applications/paideia/controllers/util.py", line 13, in copytimes\n    d.update_row(last_right = dt1, last_wrong = dt2)\n  File "/home/ian/web2py/gluon/dal.py", line 3851, in __getattr__\n    return self[key]\n  File "/home/ian/web2py/gluon/dal.py", line 3842, in __getitem__\n    return dict.__getitem__(self, key)\nKeyError: \'update_row\'\n'
p10
s.